version: '2'
services:
    mysql:
      container_name: mysql
      image: mysql:5.7.10
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: boulou
          MYSQL_PASSWORD: boulou
      volumes:
          - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
          - ./volumes/mysql/lib:/var/lib/mysql
    phpmyadmin:
        container_name: pma
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        environment:
            MYSQL_USER: boulou
            MYSQL_PASSWORD: boulou
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8001:80
    composer:
        container_name: composer
        restart: 'no'
        build:
            context: ./docker/composer
            dockerfile: Dockerfile
        image: tromboui/composer:latest
        command: install
        volumes:
            - .:/app
    php:
        container_name: php
        build: 
            context: ./docker/php-fpm
            dockerfile: Dockerfile
        entrypoint: "php bin/console server:run *:8000"
        ports:
            - '8080:8000'
        volumes:
            - .:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs:cached
        links:
            - mysql
        depends_on:
            - composer

