version: '2'
services:
    mysql:
      container_name: mysql
      image: mysql:5.7.10
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tromboui
          MYSQL_USER: boulou
          MYSQL_PASSWORD: boulou
      volumes:
          - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
          - ./volumes/mysql/lib:/var/lib/mysql
    composer:
        container_name: composer
        restart: 'no'
        build:
            context: ./docker/composer
            dockerfile: Dockerfile
        image: tromboui/composer:latest
        command: install
        volumes:
            - .:/app
    php:
        container_name: php
        build:
            context: ./docker/php-fpm
            dockerfile: Dockerfile
        entrypoint: "php bin/console server:run *:8000"
        ports:
            - '8080:8000'
        volumes:
            - .:/var/www/symfony
        links:
            - mysql
        depends_on:
            - composer
